// Do not edit. This file is machine generated by the Resource DLL Wizard.

library DBTool32;

{ITE} {DFMFileType} {C\SVN\Delphi\DBTool\Database.dfm}
{ITE} {DFMFileType} {C\SVN\Delphi\DBTool\DateiNeu.dfm}
{ITE} {DFMFileType} {C\SVN\Delphi\DBTool\EditRTF.dfm}
{ITE} {DFMFileType} {C\SVN\Delphi\DBTool\Export.dfm}
{ITE} {DFMFileType} {C\SVN\Delphi\DBTool\IbDatabaseName.dfm}
{ITE} {DFMFileType} {C\SVN\Delphi\DBTool\Import.dfm}
{ITE} {DFMFileType} {C\SVN\Delphi\DBTool\Info.dfm}
{ITE} {DFMFileType} {C\SVN\Delphi\DBTool\Main.dfm}
{ITE} {DFMFileType} {C\SVN\Delphi\DBTool\OpenMySqlDb.dfm}
{ITE} {DFMFileType} {C\SVN\Delphi\DBTool\OpenSqlDb.dfm}
{ITE} {DFMFileType} {C\SVN\Delphi\DBTool\Optionen.dfm}
{ITE} {DFMFileType} {C\SVN\Delphi\DBTool\Query.dfm}
{ITE} {DFMFileType} {C\SVN\Delphi\DBTool\Table.dfm}
{ITE} {RCFileType} {c\HS-Service\DBTool32_DRC.rc}

{$R 'C\SVN\Delphi\DBTool\Database.dfm' 'MDI_Database:TForm'}
{$R 'C\SVN\Delphi\DBTool\DateiNeu.dfm' 'DLG_DateiNeu:TForm'}
{$R 'C\SVN\Delphi\DBTool\EditRTF.dfm' 'DLG_EditRTF:TForm'}
{$R 'C\SVN\Delphi\DBTool\Export.dfm' 'DLG_Export:TForm'}
{$R 'C\SVN\Delphi\DBTool\IbDatabaseName.dfm' 'DLG_IbDatabaseName:TForm'}
{$R 'C\SVN\Delphi\DBTool\Import.dfm' 'DLG_Import:TForm'}
{$R 'C\SVN\Delphi\DBTool\Info.dfm' 'DLG_Info:TForm'}
{$R 'C\SVN\Delphi\DBTool\Main.dfm' 'DLG_Main:TForm'}
{$R 'C\SVN\Delphi\DBTool\OpenMySqlDb.dfm' 'DLG_OpenMySqlDb:TForm'}
{$R 'C\SVN\Delphi\DBTool\OpenSqlDb.dfm' 'DLG_OpenSqlDb:TForm'}
{$R 'C\SVN\Delphi\DBTool\Optionen.dfm' 'DLG_Optionen:TForm'}
{$R 'C\SVN\Delphi\DBTool\Query.dfm' 'MDI_Query:TForm'}
{$R 'C\SVN\Delphi\DBTool\Table.dfm' 'MDI_Table:TForm'}
{$R 'c\HS-Service\DBTool32_DRC.res' 'c\HS-Service\DBTool32_DRC.rc'}

{$E ENU}

begin
end.
